services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: eureka-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
      EUREKA_CLIENT_FETCH_REGISTRY: 'false'
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: 'false'

  wakandacentral:
    build: .
    container_name: wakandacentral
    ports:
      - "8080:8080"

