services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: eureka-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
      EUREKA_CLIENT_FETCH_REGISTRY: 'false'
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: 'false'

  wakandacentral:
    build: .
    container_name: wakandacentral
    ports:
      - "8080:8080"

  micoserviciotrafico:
    build: .
    container_name: microserviciotrafico
    ports:
      - "8081:8081"

  microserviciotransporte:
    build: .
    container_name: microserviciotransporte
    ports:
      - "8082:8082"

  microservicioemergencias:
    build: .
    container_name: microservicioemergencias
    ports:
      - "8083:8083"

  microservicioenergia:
    build: .
    container_name: microservicioenergia
    ports:
      - "8084:8084"

  microservicioagua:
    build: .
    container_name: microservicioagua
    ports:
      - "8085:8085"

  microservicioresiduos:
    build: .
    container_name: microservicioresiduos
    ports:
      - "8086:8086"

  microservicioseguridad:
    build: .
    container_name: microservicioseguridad
    ports:
      - "8087:8087"

  microserviciosalud:
    build: .
    container_name: microserviciosalud
    ports:
      - "8088:8088"

  microservicioeducacion:
    build: .
    container_name: microservicioeducacion
    ports:
      - "8089:8089"

  microserviciogobernanza:
    build: .
    container_name: microserviciogobernanza
    ports:
      - "8090:8090"

  microservicioconectividad:
    build: .
    container_name: microservicioconectividad
    ports:
      - "8091:8091"

  microserviciocultura:
    build: .
    container_name: microserviciocultura
    ports:
      - "8092:8092"